-- 1B: Insert Students (Independent Table)
INSERT INTO students (full_name, email, dorm_name, class_year, is_non_traditional, is_international) VALUES
('Anthony Collins', 'anthony.collins761@campus.edu', 'Draper', 'third year', 0, 0),
('Joseph Gutierrez', 'joseph.gutierrez598@campus.edu', 'Off Campus', 'first year', 0, 0),
('Jaxon Bailey', 'jaxon.bailey644@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Noah Ruiz', 'noah.ruiz299@student.campus.edu', 'MAC', 'third year', 0, 0),
('Lillian White', 'lillian.white762@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Joseph Kim', 'joseph.kim687@campus.edu', 'Pearsons', 'second year', 0, 0),
('Samuel Gutierrez', 'samuel.gutierrez206@campus.edu', 'Pearsons', 'third year', 0, 1),
('Alexander Castillo', 'alexander.castillo749@campus.edu', 'Draper', 'third year', 0, 0),
('Jackson Jimenez', 'jackson.jimenez23@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Penelope Richardson', 'penelope.richardson475@campus.edu', 'Pearsons', 'third year', 0, 0),
('Lincoln Morris', 'lincoln.morris892@campus.edu', 'Draper', 'third year', 0, 0),
('Hunter Williams', 'hunter.williams80@campus.edu', 'Off Campus', 'first year', 1, 0),
('Riley Ramirez', 'riley.ramirez407@campus.edu', 'Draper', 'third year', 0, 0),
('Michael Jimenez', 'michael.jimenez180@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Grace Hernandez', 'grace.hernandez828@campus.edu', 'MAC', 'first year', 0, 0),
('Lincoln Mendoza', 'lincoln.mendoza540@campus.edu', 'Seabury', 'second year', 0, 1),
('Ryan Bailey', 'ryan.bailey164@campus.edu', 'Off Campus', 'first year', 1, 0),
('Anthony Robinson', 'anthony.robinson102@campus.edu', 'MAC', 'fourth year', 0, 0),
('Jackson Hall', 'jackson.hall76@campus.edu', 'Off Campus', 'second year', 1, 0),
('Jackson Lewis', 'jackson.lewis716@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Ellie Martinez', 'ellie.martinez601@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Benjamin Myers', 'benjamin.myers296@campus.edu', 'Seabury', 'second year', 0, 0),
('Hannah James', 'hannah.james693@student.campus.edu', 'MAC', 'first year', 0, 1),
('Abigail Stewart', 'abigail.stewart620@student.campus.edu', 'Off Campus', 'third year', 0, 1),
('Victoria Gutierrez', 'victoria.gutierrez963@campus.edu', 'Draper', 'second year', 0, 0),
('Mila Hill', 'mila.hill786@student.campus.edu', 'Ecovillage', 'third year', 1, 1),
('Aurora Cox', 'aurora.cox879@campus.edu', 'Off Campus', 'second year', 1, 0),
('Audrey Rodriguez', 'audrey.rodriguez738@campus.edu', 'Draper', 'first year', 0, 0),
('Charlotte Peterson', 'charlotte.peterson627@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Evelyn Roberts', 'evelyn.roberts476@student.campus.edu', 'Off Campus', 'second year', 0, 1),
('Jackson Adams', 'jackson.adams72@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Lily Morris', 'lily.morris431@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Charles Gray', 'charles.gray972@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Sebastian White', 'sebastian.white988@campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Emma Anderson', 'emma.anderson317@campus.edu', 'Off Campus', 'fourth year', 1, 0),
('Jayden Walker', 'jayden.walker792@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Thomas Lopez', 'thomas.lopez675@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('David Ramos', 'david.ramos656@campus.edu', 'Draper', 'first year', 0, 0),
('Owen Flores', 'owen.flores260@campus.edu', 'Pearsons', 'second year', 0, 1),
('Addison Chavez', 'addison.chavez848@campus.edu', 'Off Campus', 'third year', 1, 0),
('Abigail Hill', 'abigail.hill638@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Lincoln Brooks', 'lincoln.brooks118@campus.edu', 'Pearsons', 'first year', 0, 0),
('Victoria Patel', 'victoria.patel293@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Thomas Taylor', 'thomas.taylor483@campus.edu', 'Seabury', 'third year', 0, 0),
('Penelope Morales', 'penelope.morales351@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Aiden Wilson', 'aiden.wilson502@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Savannah Bennett', 'savannah.bennett265@campus.edu', 'Seabury', 'second year', 0, 0),
('Alexander Reyes', 'alexander.reyes577@campus.edu', 'Draper', 'first year', 0, 0),
('Dylan Kim', 'dylan.kim596@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Stella Ward', 'stella.ward275@campus.edu', 'Off Campus', 'third year', 0, 0),
('Josiah Williams', 'josiah.williams842@student.campus.edu', 'Off Campus', 'first year', 0, 1),
('Elizabeth Cooper', 'elizabeth.cooper635@campus.edu', 'MAC', 'first year', 0, 1),
('Claire Martinez', 'claire.martinez467@student.campus.edu', 'Draper', 'first year', 0, 0),
('Lincoln Price', 'lincoln.price493@campus.edu', 'Draper', 'first year', 0, 1),
('Nathan Parker', 'nathan.parker657@campus.edu', 'Off Campus', 'second year', 0, 1),
('Julian Moore', 'julian.moore226@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('William Collins', 'william.collins700@campus.edu', 'Off Campus', 'third year', 0, 0),
('Skylar Young', 'skylar.young482@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Layla Baker', 'layla.baker917@campus.edu', 'Off Campus', 'third year', 1, 0),
('Emma Scott', 'emma.scott700@campus.edu', 'Ecovillage', 'first year', 1, 1),
('Ethan Bailey', 'ethan.bailey642@campus.edu', 'Off Campus', 'first year', 1, 0),
('Lincoln Green', 'lincoln.green86@student.campus.edu', 'Draper', 'first year', 0, 0),
('Gabriel Williams', 'gabriel.williams230@campus.edu', 'MAC', 'fourth year', 0, 0),
('Claire Turner', 'claire.turner432@campus.edu', 'Off Campus', 'first year', 0, 0),
('Christian Nelson', 'christian.nelson56@campus.edu', 'MAC', 'second year', 0, 1),
('Claire Bailey', 'claire.bailey928@student.campus.edu', 'MAC', 'fourth year', 0, 1),
('Addison Lewis', 'addison.lewis103@campus.edu', 'Draper', 'fourth year', 0, 1),
('Aubrey Clark', 'aubrey.clark497@campus.edu', 'Pearsons', 'third year', 0, 0),
('Camila Rodriguez', 'camila.rodriguez382@campus.edu', 'Seabury', 'third year', 0, 0),
('Violet Rogers', 'violet.rogers456@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Emma Sanders', 'emma.sanders21@campus.edu', 'Draper', 'second year', 0, 0),
('Anthony Young', 'anthony.young947@campus.edu', 'Draper', 'third year', 0, 0),
('Nora Castillo', 'nora.castillo518@campus.edu', 'Off Campus', 'first year', 0, 0),
('Charlotte Rodriguez', 'charlotte.rodriguez831@student.campus.edu', 'Pearsons', 'first year', 0, 1),
('Levi Collins', 'levi.collins533@student.campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Claire Myers', 'claire.myers780@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Charles Scott', 'charles.scott415@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Alexander Cox', 'alexander.cox324@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Gabriel Robinson', 'gabriel.robinson794@student.campus.edu', 'Ecovillage', 'second year', 1, 1),
('Leah Ross', 'leah.ross298@campus.edu', 'Pearsons', 'second year', 0, 0),
('Hunter Bailey', 'hunter.bailey397@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Noah Cruz', 'noah.cruz729@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Ellie Richardson', 'ellie.richardson71@student.campus.edu', 'Ecovillage', 'first year', 1, 1),
('Aria Lewis', 'aria.lewis674@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Hunter Allen', 'hunter.allen791@student.campus.edu', 'MAC', 'third year', 0, 0),
('Skylar Kim', 'skylar.kim626@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Liam Nguyen', 'liam.nguyen973@campus.edu', 'Seabury', 'first year', 0, 0),
('Caleb Watson', 'caleb.watson271@campus.edu', 'MAC', 'first year', 0, 0),
('Joshua Cruz', 'joshua.cruz366@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Ava Rodriguez', 'ava.rodriguez696@student.campus.edu', 'Off Campus', 'first year', 1, 0),
('Sophia Cox', 'sophia.cox637@campus.edu', 'Ecovillage', 'third year', 1, 1),
('Thomas Wilson', 'thomas.wilson831@campus.edu', 'Seabury', 'third year', 0, 0),
('Mila Mendoza', 'mila.mendoza383@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Ella Torres', 'ella.torres953@campus.edu', 'Seabury', 'first year', 0, 0),
('Skylar Stewart', 'skylar.stewart564@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Liam Rogers', 'liam.rogers211@student.campus.edu', 'Draper', 'second year', 0, 1),
('Wyatt Reed', 'wyatt.reed630@student.campus.edu', 'MAC', 'first year', 0, 0),
('Liam Castillo', 'liam.castillo530@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Julian Jimenez', 'julian.jimenez460@campus.edu', 'MAC', 'first year', 0, 0),
('Zoe Bailey', 'zoe.bailey506@campus.edu', 'Draper', 'second year', 0, 0),
('Hunter Thomas', 'hunter.thomas665@campus.edu', 'Pearsons', 'third year', 0, 0),
('Mia Flores', 'mia.flores615@campus.edu', 'Off Campus', 'first year', 1, 0),
('Christopher Richardson', 'christopher.richardson864@campus.edu', 'Seabury', 'first year', 0, 1),
('Penelope Rodriguez', 'penelope.rodriguez210@campus.edu', 'MAC', 'third year', 0, 0),
('Lucas Nelson', 'lucas.nelson729@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Riley Morgan', 'riley.morgan686@campus.edu', 'Pearsons', 'first year', 0, 0),
('Camila Martin', 'camila.martin128@campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Lucas Ross', 'lucas.ross290@campus.edu', 'Off Campus', 'second year', 0, 0),
('Carter Jackson', 'carter.jackson342@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Natalie Martinez', 'natalie.martinez419@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Isaac Lee', 'isaac.lee619@student.campus.edu', 'Seabury', 'third year', 0, 1),
('Emily Wright', 'emily.wright893@campus.edu', 'Seabury', 'second year', 0, 0),
('Mila Martin', 'mila.martin873@campus.edu', 'MAC', 'first year', 0, 0),
('Ellie Green', 'ellie.green88@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Samuel Gomez', 'samuel.gomez511@campus.edu', 'Pearsons', 'third year', 0, 0),
('John Lewis', 'john.lewis932@student.campus.edu', 'Draper', 'third year', 0, 1),
('Hannah Diaz', 'hannah.diaz125@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Isabella Bennett', 'isabella.bennett31@campus.edu', 'Draper', 'fourth year', 0, 1),
('Lucas Torres', 'lucas.torres224@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Ella Jackson', 'ella.jackson474@campus.edu', 'Seabury', 'first year', 0, 0),
('Stella Collins', 'stella.collins524@student.campus.edu', 'MAC', 'second year', 0, 0),
('Grace Sanders', 'grace.sanders685@campus.edu', 'Draper', 'fourth year', 0, 1),
('Mateo Parker', 'mateo.parker977@student.campus.edu', 'Off Campus', 'first year', 1, 0),
('Lily Lopez', 'lily.lopez81@student.campus.edu', 'MAC', 'first year', 0, 1),
('Charles King', 'charles.king18@campus.edu', 'Seabury', 'second year', 0, 0),
('Aubrey Torres', 'aubrey.torres152@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Elijah Moore', 'elijah.moore654@campus.edu', 'Off Campus', 'third year', 0, 0),
('Stella Walker', 'stella.walker779@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Ava Phillips', 'ava.phillips967@student.campus.edu', 'Seabury', 'third year', 0, 1),
('Ellie Murphy', 'ellie.murphy743@student.campus.edu', 'MAC', 'third year', 0, 0),
('Julian Davis', 'julian.davis567@student.campus.edu', 'MAC', 'third year', 0, 0),
('Noah Thompson', 'noah.thompson663@student.campus.edu', 'MAC', 'third year', 0, 0),
('Penelope Wilson', 'penelope.wilson193@campus.edu', 'Draper', 'third year', 0, 0),
('Addison Lewis', 'addison.lewis368@campus.edu', 'MAC', 'second year', 0, 0),
('Henry Brooks', 'henry.brooks864@student.campus.edu', 'MAC', 'second year', 0, 0),
('Isaac Wilson', 'isaac.wilson284@campus.edu', 'MAC', 'third year', 0, 0),
('Grayson Castillo', 'grayson.castillo723@campus.edu', 'Off Campus', 'fourth year', 1, 0),
('Lillian Turner', 'lillian.turner786@campus.edu', 'Off Campus', 'first year', 1, 0),
('Aiden Sanders', 'aiden.sanders239@student.campus.edu', 'Pearsons', 'second year', 0, 1),
('Avery Gomez', 'avery.gomez948@campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Aiden Castillo', 'aiden.castillo400@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Violet Martin', 'violet.martin575@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Elijah Jackson', 'elijah.jackson65@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Stella Ramos', 'stella.ramos756@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Penelope Peterson', 'penelope.peterson435@student.campus.edu', 'Pearsons', 'first year', 0, 1),
('Aurora Ortiz', 'aurora.ortiz347@student.campus.edu', 'Ecovillage', 'second year', 1, 1),
('Mila Lopez', 'mila.lopez793@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Stella Bennett', 'stella.bennett14@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Daniel Hernandez', 'daniel.hernandez976@student.campus.edu', 'Off Campus', 'fourth year', 1, 0),
('Isaac Reed', 'isaac.reed694@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Mia Adams', 'mia.adams817@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Isaiah Gonzalez', 'isaiah.gonzalez687@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Madison Cooper', 'madison.cooper725@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Ellie Foster', 'ellie.foster97@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Sofia Green', 'sofia.green570@student.campus.edu', 'Off Campus', 'second year', 0, 1),
('Ryan Cook', 'ryan.cook423@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Amelia Moore', 'amelia.moore525@campus.edu', 'Seabury', 'first year', 0, 0),
('Ethan Gutierrez', 'ethan.gutierrez775@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Abigail Carter', 'abigail.carter633@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Benjamin Howard', 'benjamin.howard137@student.campus.edu', 'MAC', 'second year', 0, 0),
('Michael Morales', 'michael.morales689@campus.edu', 'MAC', 'third year', 0, 0),
('Grace Flores', 'grace.flores364@campus.edu', 'Seabury', 'second year', 0, 1),
('Abigail Castillo', 'abigail.castillo324@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Lily Cook', 'lily.cook50@student.campus.edu', 'Off Campus', 'fourth year', 1, 0),
('Avery Wright', 'avery.wright296@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Emma Wood', 'emma.wood718@campus.edu', 'Off Campus', 'second year', 0, 0),
('Mila Taylor', 'mila.taylor448@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Wyatt Allen', 'wyatt.allen102@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Jaxon Myers', 'jaxon.myers330@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Anthony Ramos', 'anthony.ramos842@campus.edu', 'Draper', 'fourth year', 0, 0),
('Layla Hall', 'layla.hall596@campus.edu', 'Off Campus', 'second year', 0, 0),
('Aurora Patel', 'aurora.patel391@campus.edu', 'Seabury', 'first year', 0, 0),
('Noah Taylor', 'noah.taylor147@student.campus.edu', 'MAC', 'first year', 0, 0),
('Natalie Richardson', 'natalie.richardson531@student.campus.edu', 'MAC', 'first year', 0, 0),
('Benjamin Lee', 'benjamin.lee909@student.campus.edu', 'Draper', 'first year', 0, 1),
('Lillian Jimenez', 'lillian.jimenez659@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Riley Mitchell', 'riley.mitchell86@student.campus.edu', 'Seabury', 'third year', 0, 1),
('Claire Chavez', 'claire.chavez462@campus.edu', 'MAC', 'third year', 0, 0),
('Jaxon Walker', 'jaxon.walker635@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Benjamin Young', 'benjamin.young102@campus.edu', 'Seabury', 'second year', 0, 0),
('Aria Martin', 'aria.martin347@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Hunter Martinez', 'hunter.martinez681@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Joshua Ross', 'joshua.ross303@campus.edu', 'Off Campus', 'second year', 0, 0),
('Jayden Morris', 'jayden.morris983@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Brooklyn Jackson', 'brooklyn.jackson472@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Grace Parker', 'grace.parker103@student.campus.edu', 'Pearsons', 'first year', 0, 1),
('Joshua Lewis', 'joshua.lewis312@campus.edu', 'MAC', 'third year', 0, 0),
('Ella Jimenez', 'ella.jimenez564@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Matthew Morris', 'matthew.morris315@student.campus.edu', 'Off Campus', 'second year', 0, 1),
('Bella Green', 'bella.green215@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Amelia White', 'amelia.white985@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Josiah Jones', 'josiah.jones187@student.campus.edu', 'Pearsons', 'second year', 0, 1),
('Savannah Garcia', 'savannah.garcia933@student.campus.edu', 'Draper', 'third year', 0, 0),
('Savannah Lewis', 'savannah.lewis580@campus.edu', 'MAC', 'first year', 0, 0),
('Chloe Martin', 'chloe.martin926@campus.edu', 'Seabury', 'first year', 0, 0),
('Gabriel Castillo', 'gabriel.castillo856@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Lucas Stewart', 'lucas.stewart389@campus.edu', 'Seabury', 'second year', 0, 1),
('Nora Kim', 'nora.kim59@campus.edu', 'Pearsons', 'first year', 0, 0),
('Emily King', 'emily.king911@campus.edu', 'Seabury', 'second year', 0, 0),
('Zoey Brooks', 'zoey.brooks924@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Joseph Miller', 'joseph.miller45@student.campus.edu', 'Draper', 'third year', 0, 0),
('Avery Collins', 'avery.collins510@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Nathan Lewis', 'nathan.lewis127@student.campus.edu', 'MAC', 'second year', 0, 0),
('David Cook', 'david.cook510@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Lillian Scott', 'lillian.scott625@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Julian Flores', 'julian.flores448@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Samuel Gutierrez', 'samuel.gutierrez596@student.campus.edu', 'Draper', 'first year', 0, 1),
('David Scott', 'david.scott630@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Zoe Nelson', 'zoe.nelson900@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Carter Martinez', 'carter.martinez167@campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Victoria Lee', 'victoria.lee403@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Ella Smith', 'ella.smith625@student.campus.edu', 'Off Campus', 'first year', 0, 1),
('Charlotte Carter', 'charlotte.carter835@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Thomas Young', 'thomas.young527@student.campus.edu', 'MAC', 'third year', 0, 1),
('Hunter Gutierrez', 'hunter.gutierrez87@campus.edu', 'Seabury', 'third year', 0, 0),
('Luna Harris', 'luna.harris907@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Aurora Sanchez', 'aurora.sanchez397@campus.edu', 'Draper', 'first year', 0, 0),
('Nora James', 'nora.james115@student.campus.edu', 'Off Campus', 'third year', 0, 1),
('Grayson Watson', 'grayson.watson413@campus.edu', 'Seabury', 'third year', 0, 0),
('Daniel Flores', 'daniel.flores960@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Emily Ward', 'emily.ward659@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Isabella Alvarez', 'isabella.alvarez8@student.campus.edu', 'MAC', 'third year', 0, 0),
('Isaiah Wilson', 'isaiah.wilson986@student.campus.edu', 'Draper', 'third year', 0, 0),
('David Hill', 'david.hill982@student.campus.edu', 'Seabury', 'third year', 0, 1),
('Layla James', 'layla.james215@campus.edu', 'Seabury', 'second year', 0, 0),
('Emma Gonzalez', 'emma.gonzalez514@campus.edu', 'Draper', 'first year', 0, 0),
('Mila Howard', 'mila.howard614@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Isabella Garcia', 'isabella.garcia962@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('David Smith', 'david.smith679@campus.edu', 'Seabury', 'third year', 0, 0),
('James Ortiz', 'james.ortiz111@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Christopher Reyes', 'christopher.reyes319@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Hazel Allen', 'hazel.allen592@campus.edu', 'Seabury', 'third year', 0, 0),
('Mateo Kim', 'mateo.kim448@student.campus.edu', 'Seabury', 'third year', 0, 1),
('Isaiah Kelly', 'isaiah.kelly255@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Ava Williams', 'ava.williams586@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Leah Miller', 'leah.miller470@campus.edu', 'Off Campus', 'first year', 0, 1),
('Riley Scott', 'riley.scott311@campus.edu', 'Draper', 'third year', 0, 0),
('Lily Young', 'lily.young580@student.campus.edu', 'Ecovillage', 'first year', 1, 1),
('Zoey Davis', 'zoey.davis209@student.campus.edu', 'MAC', 'fourth year', 0, 1),
('Emily Wilson', 'emily.wilson357@student.campus.edu', 'MAC', 'third year', 0, 1),
('Madison Morgan', 'madison.morgan976@campus.edu', 'Ecovillage', 'first year', 1, 1),
('Lily Cooper', 'lily.cooper671@campus.edu', 'Draper', 'second year', 0, 1),
('Matthew Lopez', 'matthew.lopez642@student.campus.edu', 'Off Campus', 'first year', 0, 1),
('Luke Myers', 'luke.myers11@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Elijah Watson', 'elijah.watson987@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Aaron Davis', 'aaron.davis17@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Joseph Long', 'joseph.long43@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Joshua Ramirez', 'joshua.ramirez577@student.campus.edu', 'MAC', 'second year', 0, 0),
('Michael White', 'michael.white303@campus.edu', 'Draper', 'first year', 0, 1),
('Abigail Mitchell', 'abigail.mitchell385@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('James Harris', 'james.harris843@campus.edu', 'Off Campus', 'third year', 0, 1),
('Liam Sanchez', 'liam.sanchez934@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Riley Cook', 'riley.cook24@student.campus.edu', 'MAC', 'fourth year', 0, 1),
('Victoria Ross', 'victoria.ross848@campus.edu', 'Pearsons', 'third year', 0, 0),
('Christian Peterson', 'christian.peterson162@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Jackson Wilson', 'jackson.wilson754@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Eleanor Ortiz', 'eleanor.ortiz795@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Aria Brooks', 'aria.brooks164@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Anthony Robinson', 'anthony.robinson572@campus.edu', 'Draper', 'fourth year', 0, 0),
('Hunter Mitchell', 'hunter.mitchell989@campus.edu', 'Pearsons', 'second year', 0, 0),
('Owen Chavez', 'owen.chavez924@campus.edu', 'Pearsons', 'first year', 0, 0),
('Jayden Reyes', 'jayden.reyes717@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Chloe Martin', 'chloe.martin471@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Victoria Taylor', 'victoria.taylor828@campus.edu', 'MAC', 'fourth year', 0, 1),
('Joseph Hall', 'joseph.hall786@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Michael Hernandez', 'michael.hernandez476@campus.edu', 'Draper', 'second year', 0, 0),
('Elizabeth Roberts', 'elizabeth.roberts77@campus.edu', 'Draper', 'first year', 0, 1),
('Elizabeth Cruz', 'elizabeth.cruz409@campus.edu', 'Off Campus', 'second year', 0, 0),
('Grace Rivera', 'grace.rivera67@campus.edu', 'Pearsons', 'second year', 0, 0),
('Anthony Thompson', 'anthony.thompson633@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Riley Campbell', 'riley.campbell901@student.campus.edu', 'MAC', 'first year', 0, 1),
('Ethan Morgan', 'ethan.morgan519@campus.edu', 'Seabury', 'first year', 0, 1),
('Hannah Hernandez', 'hannah.hernandez839@campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Anthony Miller', 'anthony.miller290@student.campus.edu', 'Draper', 'third year', 0, 0),
('Noah Moore', 'noah.moore4@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Aiden Cox', 'aiden.cox681@campus.edu', 'Seabury', 'second year', 0, 1),
('Zoey Howard', 'zoey.howard416@student.campus.edu', 'MAC', 'first year', 0, 0),
('Ethan Brown', 'ethan.brown152@campus.edu', 'Draper', 'fourth year', 0, 1),
('Abigail Myers', 'abigail.myers373@student.campus.edu', 'Draper', 'first year', 0, 0),
('Charles Miller', 'charles.miller428@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Scarlett Hernandez', 'scarlett.hernandez716@campus.edu', 'Ecovillage', 'third year', 1, 0),
('Jack Lee', 'jack.lee685@student.campus.edu', 'MAC', 'first year', 0, 0),
('Samuel Kim', 'samuel.kim539@student.campus.edu', 'MAC', 'third year', 0, 0),
('Aubrey Williams', 'aubrey.williams990@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Olivia Wright', 'olivia.wright488@campus.edu', 'MAC', 'third year', 0, 0),
('Penelope Sanders', 'penelope.sanders528@student.campus.edu', 'Draper', 'first year', 0, 0),
('Charlotte Rogers', 'charlotte.rogers765@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Zoe Thomas', 'zoe.thomas333@campus.edu', 'Seabury', 'second year', 0, 0),
('Olivia Brown', 'olivia.brown723@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Scarlett Richardson', 'scarlett.richardson590@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Aaron Reed', 'aaron.reed36@campus.edu', 'Seabury', 'second year', 0, 0),
('Camila Flores', 'camila.flores613@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Brooklyn Jones', 'brooklyn.jones199@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Avery Hill', 'avery.hill992@campus.edu', 'Ecovillage', 'first year', 1, 1),
('Olivia Cook', 'olivia.cook319@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Jaxon Bennett', 'jaxon.bennett414@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Addison Richardson', 'addison.richardson87@campus.edu', 'Pearsons', 'third year', 0, 0),
('David Castillo', 'david.castillo671@campus.edu', 'Seabury', 'third year', 0, 0),
('Daniel Sanchez', 'daniel.sanchez902@student.campus.edu', 'MAC', 'first year', 0, 0),
('Layla Evans', 'layla.evans8@student.campus.edu', 'Draper', 'second year', 0, 0),
('Emily Sanchez', 'emily.sanchez42@student.campus.edu', 'MAC', 'third year', 0, 0),
('Harper Castillo', 'harper.castillo241@campus.edu', 'MAC', 'third year', 0, 1),
('Amelia Brooks', 'amelia.brooks959@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Evelyn Gray', 'evelyn.gray153@campus.edu', 'Off Campus', 'third year', 0, 0),
('Zoey Ruiz', 'zoey.ruiz550@student.campus.edu', 'MAC', 'third year', 0, 1),
('Addison Johnson', 'addison.johnson971@campus.edu', 'Ecovillage', 'second year', 1, 1),
('Joseph Torres', 'joseph.torres703@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Isaac Baker', 'isaac.baker155@campus.edu', 'MAC', 'second year', 0, 0),
('Mila Scott', 'mila.scott898@campus.edu', 'Pearsons', 'second year', 0, 0),
('Riley Davis', 'riley.davis687@campus.edu', 'MAC', 'fourth year', 0, 0),
('Noah Gomez', 'noah.gomez460@campus.edu', 'Draper', 'fourth year', 0, 0),
('Amelia Cook', 'amelia.cook469@student.campus.edu', 'Draper', 'third year', 0, 0),
('Joshua Ramos', 'joshua.ramos535@campus.edu', 'Seabury', 'third year', 0, 0),
('Joseph Chavez', 'joseph.chavez450@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Lily Wood', 'lily.wood472@campus.edu', 'Draper', 'second year', 0, 0),
('Hunter Myers', 'hunter.myers438@campus.edu', 'Draper', 'third year', 0, 0),
('Andrew Wright', 'andrew.wright880@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Emily Scott', 'emily.scott655@student.campus.edu', 'MAC', 'first year', 0, 0),
('Evelyn White', 'evelyn.white4@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Nora Long', 'nora.long189@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Bella Reed', 'bella.reed240@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Hannah Nguyen', 'hannah.nguyen849@campus.edu', 'Draper', 'first year', 0, 0),
('Jayden Rodriguez', 'jayden.rodriguez463@campus.edu', 'MAC', 'second year', 0, 1),
('Amelia Morris', 'amelia.morris685@campus.edu', 'Pearsons', 'first year', 0, 0),
('Layla Foster', 'layla.foster53@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Nathan Baker', 'nathan.baker287@campus.edu', 'Pearsons', 'first year', 0, 0),
('Elizabeth Baker', 'elizabeth.baker842@campus.edu', 'Pearsons', 'first year', 0, 0),
('Olivia Flores', 'olivia.flores939@student.campus.edu', 'MAC', 'second year', 0, 0),
('Olivia Ramirez', 'olivia.ramirez832@campus.edu', 'Draper', 'third year', 0, 0),
('Anthony Jackson', 'anthony.jackson150@student.campus.edu', 'MAC', 'third year', 0, 0),
('Audrey Hall', 'audrey.hall854@student.campus.edu', 'MAC', 'first year', 0, 1),
('Joseph Morales', 'joseph.morales820@campus.edu', 'Off Campus', 'first year', 0, 0),
('Hannah Parker', 'hannah.parker702@campus.edu', 'Draper', 'third year', 0, 0),
('Joshua Rivera', 'joshua.rivera897@campus.edu', 'Ecovillage', 'first year', 1, 0),
('Henry Cook', 'henry.cook838@student.campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Owen Jackson', 'owen.jackson990@student.campus.edu', 'Draper', 'third year', 0, 0),
('Luna Brooks', 'luna.brooks631@student.campus.edu', 'Draper', 'second year', 0, 0),
('Harper Lopez', 'harper.lopez141@student.campus.edu', 'MAC', 'second year', 0, 0),
('Josiah Peterson', 'josiah.peterson82@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Elizabeth Hall', 'elizabeth.hall608@campus.edu', 'Draper', 'fourth year', 0, 0),
('Joshua Williams', 'joshua.williams132@campus.edu', 'Pearsons', 'second year', 0, 0),
('Audrey Davis', 'audrey.davis202@campus.edu', 'Draper', 'second year', 0, 0),
('Harper Lee', 'harper.lee671@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Hazel James', 'hazel.james78@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Josiah Young', 'josiah.young784@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Stella Garcia', 'stella.garcia477@campus.edu', 'Seabury', 'third year', 0, 0),
('Mila Rivera', 'mila.rivera380@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Samuel Cooper', 'samuel.cooper154@student.campus.edu', 'Draper', 'first year', 0, 0),
('Luna Bennett', 'luna.bennett805@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Henry Hughes', 'henry.hughes206@student.campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Christian Castillo', 'christian.castillo160@student.campus.edu', 'Draper', 'third year', 0, 0),
('Isabella Morales', 'isabella.morales638@campus.edu', 'Seabury', 'first year', 0, 0),
('Owen Johnson', 'owen.johnson667@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Ava Anderson', 'ava.anderson612@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Joseph Thompson', 'joseph.thompson581@campus.edu', 'Pearsons', 'second year', 0, 0),
('Aurora Anderson', 'aurora.anderson275@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Sebastian White', 'sebastian.white338@campus.edu', 'Draper', 'third year', 0, 1),
('Sofia Diaz', 'sofia.diaz759@campus.edu', 'Draper', 'fourth year', 0, 0),
('Bella Mendoza', 'bella.mendoza881@student.campus.edu', 'MAC', 'second year', 0, 0),
('Nora Kelly', 'nora.kelly769@student.campus.edu', 'MAC', 'first year', 0, 0),
('Ella Lee', 'ella.lee130@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Anthony Chavez', 'anthony.chavez774@campus.edu', 'MAC', 'third year', 0, 1),
('Ella Lopez', 'ella.lopez42@campus.edu', 'Draper', 'third year', 0, 1),
('Luna Howard', 'luna.howard91@campus.edu', 'MAC', 'fourth year', 0, 0),
('David Reed', 'david.reed16@campus.edu', 'MAC', 'third year', 0, 0),
('Sofia Clark', 'sofia.clark976@student.campus.edu', 'Seabury', 'first year', 0, 1),
('Lillian Brooks', 'lillian.brooks552@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Camila Ross', 'camila.ross30@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Aria Johnson', 'aria.johnson912@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Josiah Wood', 'josiah.wood617@campus.edu', 'Draper', 'second year', 0, 0),
('Sebastian Watson', 'sebastian.watson617@student.campus.edu', 'MAC', 'third year', 0, 0),
('Mila Brooks', 'mila.brooks948@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Dylan Martin', 'dylan.martin157@campus.edu', 'Off Campus', 'third year', 0, 0),
('Isaac Gray', 'isaac.gray477@student.campus.edu', 'Off Campus', 'second year', 0, 1),
('Anthony Perez', 'anthony.perez559@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Chloe Hill', 'chloe.hill967@student.campus.edu', 'MAC', 'third year', 0, 0),
('Chloe Diaz', 'chloe.diaz427@campus.edu', 'Pearsons', 'first year', 0, 0),
('Mateo Hernandez', 'mateo.hernandez255@student.campus.edu', 'Draper', 'second year', 0, 1),
('Ava Jackson', 'ava.jackson861@campus.edu', 'MAC', 'first year', 0, 0),
('Olivia Gray', 'olivia.gray834@student.campus.edu', 'Draper', 'second year', 0, 0),
('Addison Evans', 'addison.evans96@campus.edu', 'MAC', 'first year', 0, 0),
('Chloe Campbell', 'chloe.campbell169@campus.edu', 'MAC', 'first year', 0, 0),
('Grayson Smith', 'grayson.smith93@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Michael Morris', 'michael.morris856@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Sophia Sanchez', 'sophia.sanchez255@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Caleb Hernandez', 'caleb.hernandez798@campus.edu', 'Pearsons', 'first year', 0, 0),
('Owen White', 'owen.white324@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Samuel Williams', 'samuel.williams452@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Alexander Watson', 'alexander.watson906@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Sophia Ruiz', 'sophia.ruiz771@campus.edu', 'Ecovillage', 'third year', 1, 0),
('Lincoln Williams', 'lincoln.williams563@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Chloe Kelly', 'chloe.kelly449@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Thomas Hernandez', 'thomas.hernandez472@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Aria Thomas', 'aria.thomas424@campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Christian Garcia', 'christian.garcia178@campus.edu', 'Draper', 'first year', 0, 0),
('Christopher Garcia', 'christopher.garcia569@student.campus.edu', 'Draper', 'first year', 0, 0),
('Hazel Clark', 'hazel.clark260@campus.edu', 'Pearsons', 'third year', 0, 0),
('Julian Diaz', 'julian.diaz954@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Madison Anderson', 'madison.anderson258@campus.edu', 'MAC', 'first year', 0, 0),
('Camila Reyes', 'camila.reyes211@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Michael Jimenez', 'michael.jimenez513@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Owen Rodriguez', 'owen.rodriguez576@campus.edu', 'Pearsons', 'first year', 0, 0),
('Eleanor Sanders', 'eleanor.sanders795@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Grayson Ramirez', 'grayson.ramirez480@campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Audrey Gomez', 'audrey.gomez304@student.campus.edu', 'Draper', 'third year', 0, 0),
('Aaron Williams', 'aaron.williams56@student.campus.edu', 'MAC', 'first year', 0, 1),
('Sophia Parker', 'sophia.parker870@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Benjamin Cooper', 'benjamin.cooper196@student.campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Brooklyn Kim', 'brooklyn.kim864@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Noah Foster', 'noah.foster562@student.campus.edu', 'MAC', 'second year', 0, 1),
('Aurora Collins', 'aurora.collins168@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Aaron Gutierrez', 'aaron.gutierrez895@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Camila Kim', 'camila.kim133@student.campus.edu', 'Off Campus', 'first year', 0, 1),
('Levi Mendoza', 'levi.mendoza32@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Skylar Carter', 'skylar.carter252@student.campus.edu', 'Draper', 'second year', 0, 1),
('Matthew Jackson', 'matthew.jackson349@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Amelia Torres', 'amelia.torres285@campus.edu', 'Draper', 'third year', 0, 1),
('Alexander Hall', 'alexander.hall90@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Luke Allen', 'luke.allen358@campus.edu', 'MAC', 'fourth year', 0, 1),
('Hazel Murphy', 'hazel.murphy856@student.campus.edu', 'Draper', 'third year', 0, 1),
('Ella Brown', 'ella.brown660@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Camila Torres', 'camila.torres38@campus.edu', 'Off Campus', 'third year', 0, 0),
('Bella Hughes', 'bella.hughes760@student.campus.edu', 'MAC', 'second year', 0, 0),
('Mila Evans', 'mila.evans49@student.campus.edu', 'Draper', 'second year', 0, 0),
('Aubrey Hughes', 'aubrey.hughes1@campus.edu', 'Seabury', 'second year', 0, 0),
('Amelia Price', 'amelia.price457@campus.edu', 'Draper', 'third year', 0, 0),
('Elizabeth Mendoza', 'elizabeth.mendoza714@student.campus.edu', 'Draper', 'second year', 0, 0),
('Hunter Chavez', 'hunter.chavez491@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Layla Lewis', 'layla.lewis511@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Lincoln Jackson', 'lincoln.jackson212@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Joseph Bailey', 'joseph.bailey785@student.campus.edu', 'Draper', 'third year', 0, 0),
('Aaron Anderson', 'aaron.anderson303@campus.edu', 'MAC', 'third year', 0, 0),
('Elijah Rogers', 'elijah.rogers725@student.campus.edu', 'MAC', 'second year', 0, 0),
('Levi Perez', 'levi.perez601@student.campus.edu', 'Draper', 'third year', 0, 1),
('Mia Green', 'mia.green385@campus.edu', 'Pearsons', 'second year', 0, 0),
('Zoe Ramos', 'zoe.ramos368@student.campus.edu', 'Seabury', 'second year', 0, 1),
('Aria Alvarez', 'aria.alvarez336@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Sophia Jimenez', 'sophia.jimenez24@campus.edu', 'Draper', 'second year', 0, 0),
('Luna Lee', 'luna.lee355@student.campus.edu', 'MAC', 'second year', 0, 0),
('Grayson Anderson', 'grayson.anderson657@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Ava Harris', 'ava.harris884@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Samuel Martinez', 'samuel.martinez999@student.campus.edu', 'Pearsons', 'second year', 0, 1),
('Aaron Clark', 'aaron.clark654@student.campus.edu', 'Draper', 'first year', 0, 0),
('Mateo Roberts', 'mateo.roberts858@campus.edu', 'Seabury', 'second year', 0, 0),
('Camila Gonzalez', 'camila.gonzalez280@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Levi Green', 'levi.green993@campus.edu', 'MAC', 'third year', 0, 0),
('Camila Brown', 'camila.brown957@campus.edu', 'Seabury', 'second year', 0, 0),
('Joseph Wright', 'joseph.wright221@student.campus.edu', 'MAC', 'third year', 0, 0),
('Michael Gray', 'michael.gray875@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('William Allen', 'william.allen559@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Lincoln Chavez', 'lincoln.chavez101@campus.edu', 'Off Campus', 'second year', 0, 0),
('Samuel Torres', 'samuel.torres999@student.campus.edu', 'Draper', 'first year', 0, 1),
('Grace Ortiz', 'grace.ortiz510@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Camila Chavez', 'camila.chavez556@campus.edu', 'Seabury', 'second year', 0, 0),
('Christopher Bailey', 'christopher.bailey679@campus.edu', 'Pearsons', 'first year', 0, 0),
('Natalie Clark', 'natalie.clark147@campus.edu', 'Pearsons', 'second year', 0, 0),
('Scarlett Mendoza', 'scarlett.mendoza361@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Samuel Turner', 'samuel.turner818@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Lucas Gomez', 'lucas.gomez801@campus.edu', 'Off Campus', 'first year', 0, 0),
('Sebastian Ward', 'sebastian.ward193@campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Christian Murphy', 'christian.murphy81@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Sofia Miller', 'sofia.miller639@campus.edu', 'Seabury', 'second year', 0, 0),
('Charles Ortiz', 'charles.ortiz131@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Zoey Thompson', 'zoey.thompson19@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Aaron Patel', 'aaron.patel412@campus.edu', 'Off Campus', 'third year', 0, 1),
('Andrew Reed', 'andrew.reed583@campus.edu', 'Pearsons', 'third year', 0, 0),
('Evelyn Mendoza', 'evelyn.mendoza728@campus.edu', 'Off Campus', 'third year', 0, 1),
('Abigail Lewis', 'abigail.lewis847@campus.edu', 'Pearsons', 'first year', 0, 1),
('Charlotte Gray', 'charlotte.gray888@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Violet Cruz', 'violet.cruz432@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Aiden Robinson', 'aiden.robinson63@campus.edu', 'Draper', 'fourth year', 0, 0),
('Amelia Torres', 'amelia.torres447@campus.edu', 'Pearsons', 'first year', 0, 0),
('Skylar Reed', 'skylar.reed28@campus.edu', 'Seabury', 'third year', 0, 1),
('Stella Sanchez', 'stella.sanchez257@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Luke Rivera', 'luke.rivera996@campus.edu', 'Ecovillage', 'first year', 1, 1),
('David Patel', 'david.patel131@campus.edu', 'MAC', 'third year', 0, 0),
('Ellie Evans', 'ellie.evans635@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Grace Bennett', 'grace.bennett481@student.campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Jayden Gray', 'jayden.gray15@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Carter Lopez', 'carter.lopez140@campus.edu', 'Pearsons', 'first year', 0, 0),
('Jayden Price', 'jayden.price61@campus.edu', 'Draper', 'fourth year', 0, 0),
('Violet Roberts', 'violet.roberts963@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Leah Turner', 'leah.turner934@campus.edu', 'Draper', 'fourth year', 0, 0),
('Madison Cruz', 'madison.cruz578@campus.edu', 'Ecovillage', 'second year', 1, 0),
('John Morris', 'john.morris4@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Ryan Richardson', 'ryan.richardson108@campus.edu', 'MAC', 'third year', 0, 0),
('Jaxon Lopez', 'jaxon.lopez47@campus.edu', 'Off Campus', 'third year', 0, 0),
('Camila Lee', 'camila.lee979@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Jack Hill', 'jack.hill592@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Sebastian Price', 'sebastian.price521@campus.edu', 'Pearsons', 'second year', 0, 0),
('Dylan Gonzalez', 'dylan.gonzalez14@campus.edu', 'Pearsons', 'first year', 0, 0),
('Natalie Cook', 'natalie.cook529@campus.edu', 'Draper', 'second year', 0, 0),
('Gabriel Peterson', 'gabriel.peterson476@student.campus.edu', 'Draper', 'second year', 0, 1),
('Victoria Bailey', 'victoria.bailey958@campus.edu', 'MAC', 'second year', 0, 0),
('Audrey Anderson', 'audrey.anderson272@student.campus.edu', 'Seabury', 'first year', 0, 1),
('Harper Evans', 'harper.evans275@campus.edu', 'Pearsons', 'third year', 0, 0),
('Stella Peterson', 'stella.peterson907@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Julian Ortiz', 'julian.ortiz9@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Michael Turner', 'michael.turner40@student.campus.edu', 'MAC', 'first year', 0, 0),
('Levi Howard', 'levi.howard564@campus.edu', 'MAC', 'first year', 0, 0),
('Lillian Bennett', 'lillian.bennett477@student.campus.edu', 'Draper', 'first year', 0, 0),
('Owen Turner', 'owen.turner570@student.campus.edu', 'Seabury', 'second year', 0, 1),
('Aiden Hughes', 'aiden.hughes713@campus.edu', 'Ecovillage', 'second year', 1, 1),
('Evelyn Adams', 'evelyn.adams160@campus.edu', 'Draper', 'fourth year', 0, 1),
('Luna Rivera', 'luna.rivera924@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Owen Garcia', 'owen.garcia555@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Oliver Robinson', 'oliver.robinson508@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Nathan Garcia', 'nathan.garcia693@student.campus.edu', 'Draper', 'third year', 0, 0),
('Amelia Ward', 'amelia.ward398@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Lillian King', 'lillian.king283@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Savannah Richardson', 'savannah.richardson418@campus.edu', 'Draper', 'third year', 0, 0),
('Chloe Ross', 'chloe.ross802@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Ella Chavez', 'ella.chavez165@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Jaxon Chavez', 'jaxon.chavez137@campus.edu', 'MAC', 'fourth year', 0, 0),
('Hannah Morgan', 'hannah.morgan236@campus.edu', 'Pearsons', 'second year', 0, 0),
('Oliver Anderson', 'oliver.anderson627@student.campus.edu', 'Draper', 'first year', 0, 1),
('Grayson Cook', 'grayson.cook415@campus.edu', 'Draper', 'third year', 0, 0),
('Natalie Castillo', 'natalie.castillo410@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Riley Cruz', 'riley.cruz853@student.campus.edu', 'Pearsons', 'second year', 0, 1),
('Jaxon Carter', 'jaxon.carter802@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Audrey Alvarez', 'audrey.alvarez36@campus.edu', 'Ecovillage', 'third year', 1, 0),
('Emma Long', 'emma.long801@student.campus.edu', 'Draper', 'third year', 0, 0),
('Lily Jones', 'lily.jones111@student.campus.edu', 'MAC', 'second year', 0, 0),
('Andrew Price', 'andrew.price773@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Ella Murphy', 'ella.murphy438@campus.edu', 'Off Campus', 'third year', 0, 0),
('Daniel Kelly', 'daniel.kelly15@campus.edu', 'Draper', 'fourth year', 0, 0),
('Caleb Gomez', 'caleb.gomez564@campus.edu', 'Draper', 'second year', 0, 0),
('Joshua Carter', 'joshua.carter681@campus.edu', 'Off Campus', 'first year', 0, 0),
('Michael Castillo', 'michael.castillo284@student.campus.edu', 'Ecovillage', 'third year', 1, 1),
('Aurora Anderson', 'aurora.anderson433@student.campus.edu', 'Draper', 'second year', 0, 1),
('Elijah Rivera', 'elijah.rivera128@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Aurora Lewis', 'aurora.lewis599@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Claire Turner', 'claire.turner798@campus.edu', 'Seabury', 'third year', 0, 0),
('Addison Alvarez', 'addison.alvarez828@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Henry Harris', 'henry.harris800@campus.edu', 'Draper', 'first year', 0, 0),
('Aurora White', 'aurora.white871@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Owen Peterson', 'owen.peterson459@campus.edu', 'Off Campus', 'first year', 0, 0),
('Violet Clark', 'violet.clark982@campus.edu', 'Ecovillage', 'second year', 1, 0),
('John Gonzalez', 'john.gonzalez560@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Henry Chavez', 'henry.chavez10@student.campus.edu', 'Ecovillage', 'first year', 1, 1),
('Nora White', 'nora.white872@student.campus.edu', 'Seabury', 'second year', 0, 1),
('Owen Roberts', 'owen.roberts941@student.campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Mateo Edwards', 'mateo.edwards897@campus.edu', 'Draper', 'fourth year', 0, 0),
('Elijah Davis', 'elijah.davis814@campus.edu', 'Draper', 'third year', 0, 1),
('Grayson Rogers', 'grayson.rogers884@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Owen Brooks', 'owen.brooks132@student.campus.edu', 'Draper', 'first year', 0, 0),
('Isaac Martin', 'isaac.martin524@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Aaron Peterson', 'aaron.peterson694@student.campus.edu', 'Draper', 'second year', 0, 1),
('Mila King', 'mila.king209@campus.edu', 'MAC', 'third year', 0, 0),
('Hannah Brown', 'hannah.brown285@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Andrew Brown', 'andrew.brown969@campus.edu', 'Seabury', 'first year', 0, 0),
('Owen Richardson', 'owen.richardson235@campus.edu', 'Pearsons', 'third year', 0, 0),
('Hunter Foster', 'hunter.foster524@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Amelia Wilson', 'amelia.wilson688@student.campus.edu', 'MAC', 'second year', 0, 0),
('Layla Martinez', 'layla.martinez237@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Amelia James', 'amelia.james719@campus.edu', 'Seabury', 'fourth year', 0, 1),
('Sebastian Bailey', 'sebastian.bailey586@campus.edu', 'Off Campus', 'third year', 0, 1),
('Jackson Miller', 'jackson.miller226@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Natalie Torres', 'natalie.torres223@campus.edu', 'Off Campus', 'third year', 0, 1),
('Abigail Sanders', 'abigail.sanders857@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Ryan Ward', 'ryan.ward903@campus.edu', 'Draper', 'second year', 0, 0),
('Ava Cox', 'ava.cox28@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Joshua Hill', 'joshua.hill463@student.campus.edu', 'MAC', 'second year', 0, 0),
('Ava Carter', 'ava.carter34@campus.edu', 'Seabury', 'second year', 0, 0),
('Ethan Torres', 'ethan.torres112@campus.edu', 'MAC', 'second year', 0, 0),
('Mateo Richardson', 'mateo.richardson195@student.campus.edu', 'Off Campus', 'second year', 0, 1),
('Ellie Thomas', 'ellie.thomas86@campus.edu', 'MAC', 'fourth year', 0, 0),
('David Lopez', 'david.lopez960@campus.edu', 'Ecovillage', 'first year', 1, 0),
('Leah Patel', 'leah.patel301@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Aurora Robinson', 'aurora.robinson237@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Aria Edwards', 'aria.edwards83@student.campus.edu', 'Pearsons', 'third year', 0, 1),
('Riley Parker', 'riley.parker136@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Andrew Nelson', 'andrew.nelson407@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Oliver Cruz', 'oliver.cruz31@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Jaxon Moore', 'jaxon.moore20@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('James Morgan', 'james.morgan301@campus.edu', 'MAC', 'first year', 0, 0),
('Sofia Ramos', 'sofia.ramos314@campus.edu', 'Ecovillage', 'third year', 1, 1),
('Benjamin Wilson', 'benjamin.wilson564@campus.edu', 'Pearsons', 'second year', 0, 1),
('Mila Reyes', 'mila.reyes162@campus.edu', 'MAC', 'second year', 0, 0),
('Scarlett Sanders', 'scarlett.sanders863@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('John Hall', 'john.hall730@campus.edu', 'Pearsons', 'third year', 0, 0),
('Harper James', 'harper.james578@student.campus.edu', 'MAC', 'first year', 0, 0),
('Madison Ramirez', 'madison.ramirez453@campus.edu', 'Pearsons', 'second year', 0, 0),
('Olivia Howard', 'olivia.howard951@student.campus.edu', 'MAC', 'second year', 0, 0),
('Scarlett Cruz', 'scarlett.cruz971@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('John Wright', 'john.wright147@campus.edu', 'MAC', 'fourth year', 0, 0),
('Natalie Carter', 'natalie.carter216@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Lily Ward', 'lily.ward880@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Christian Lee', 'christian.lee104@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Chloe Martinez', 'chloe.martinez343@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Alexander Ward', 'alexander.ward206@campus.edu', 'Pearsons', 'first year', 0, 0),
('Nora Bailey', 'nora.bailey255@student.campus.edu', 'Seabury', 'first year', 0, 0),
('William Parker', 'william.parker216@campus.edu', 'Draper', 'first year', 0, 0),
('Isabella Rogers', 'isabella.rogers184@student.campus.edu', 'Draper', 'first year', 0, 0),
('Abigail Collins', 'abigail.collins631@student.campus.edu', 'Draper', 'third year', 0, 0),
('Lily Lewis', 'lily.lewis452@campus.edu', 'Draper', 'third year', 0, 0),
('Violet Gonzalez', 'violet.gonzalez123@student.campus.edu', 'Ecovillage', 'fourth year', 1, 1),
('Zoe Kelly', 'zoe.kelly998@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Isaiah Ward', 'isaiah.ward32@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Penelope Nelson', 'penelope.nelson637@campus.edu', 'Draper', 'third year', 0, 1),
('Eleanor Anderson', 'eleanor.anderson891@campus.edu', 'Pearsons', 'third year', 0, 0),
('Madison Chavez', 'madison.chavez911@student.campus.edu', 'Draper', 'third year', 0, 1),
('Carter Phillips', 'carter.phillips278@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Charlotte Nguyen', 'charlotte.nguyen112@campus.edu', 'Draper', 'third year', 0, 0),
('Jayden Richardson', 'jayden.richardson57@campus.edu', 'Draper', 'first year', 0, 0),
('Joshua Smith', 'joshua.smith641@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Joshua Adams', 'joshua.adams489@student.campus.edu', 'MAC', 'first year', 0, 0),
('Alexander Williams', 'alexander.williams442@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('David Allen', 'david.allen144@campus.edu', 'Off Campus', 'third year', 0, 0),
('Riley Williams', 'riley.williams272@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Isaac Kelly', 'isaac.kelly173@campus.edu', 'Draper', 'first year', 0, 0),
('Daniel Walker', 'daniel.walker432@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Mateo Edwards', 'mateo.edwards147@campus.edu', 'Seabury', 'second year', 0, 1),
('Hunter Price', 'hunter.price580@campus.edu', 'Pearsons', 'third year', 0, 0),
('Mila Wilson', 'mila.wilson416@student.campus.edu', 'Seabury', 'third year', 0, 1),
('Sofia Foster', 'sofia.foster467@campus.edu', 'MAC', 'second year', 0, 1),
('Carter Torres', 'carter.torres112@campus.edu', 'Ecovillage', 'second year', 1, 0),
('William Martinez', 'william.martinez655@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Benjamin Williams', 'benjamin.williams44@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Grace Lopez', 'grace.lopez783@campus.edu', 'Draper', 'first year', 0, 0),
('Levi Cooper', 'levi.cooper933@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Daniel Phillips', 'daniel.phillips521@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Isaac Green', 'isaac.green310@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Alexander Ortiz', 'alexander.ortiz964@campus.edu', 'Off Campus', 'second year', 0, 0),
('Savannah Smith', 'savannah.smith432@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Ellie Jimenez', 'ellie.jimenez140@campus.edu', 'MAC', 'third year', 0, 0),
('Jaxon Evans', 'jaxon.evans734@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Mia Martin', 'mia.martin358@campus.edu', 'Pearsons', 'third year', 0, 0),
('Michael Collins', 'michael.collins532@student.campus.edu', 'Draper', 'third year', 0, 0),
('Skylar Rivera', 'skylar.rivera62@campus.edu', 'Off Campus', 'third year', 0, 0),
('Isaiah Martinez', 'isaiah.martinez879@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Olivia Morris', 'olivia.morris814@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Madison Allen', 'madison.allen288@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Levi Cooper', 'levi.cooper129@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Dylan Robinson', 'dylan.robinson499@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Oliver Torres', 'oliver.torres71@student.campus.edu', 'Draper', 'second year', 0, 1),
('Emily Hernandez', 'emily.hernandez662@campus.edu', 'Seabury', 'fourth year', 0, 1),
('Ava Evans', 'ava.evans804@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Leah Brown', 'leah.brown18@student.campus.edu', 'MAC', 'second year', 0, 0),
('Avery Perez', 'avery.perez226@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Daniel Cooper', 'daniel.cooper91@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Josiah Ruiz', 'josiah.ruiz102@campus.edu', 'Seabury', 'second year', 0, 0),
('Anthony Watson', 'anthony.watson453@student.campus.edu', 'MAC', 'first year', 0, 0),
('Noah Foster', 'noah.foster693@campus.edu', 'Pearsons', 'second year', 0, 0),
('Owen Lee', 'owen.lee192@student.campus.edu', 'MAC', 'second year', 0, 0),
('Ava Gomez', 'ava.gomez420@campus.edu', 'Off Campus', 'first year', 0, 1),
('Aurora Ward', 'aurora.ward384@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Jack Morales', 'jack.morales924@student.campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Ryan King', 'ryan.king627@student.campus.edu', 'MAC', 'third year', 0, 0),
('Joshua Morales', 'joshua.morales901@campus.edu', 'Draper', 'second year', 0, 0),
('Leah Wood', 'leah.wood249@campus.edu', 'MAC', 'second year', 0, 0),
('Nathan Jimenez', 'nathan.jimenez358@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Hannah Patel', 'hannah.patel406@student.campus.edu', 'Off Campus', 'first year', 0, 1),
('Hazel Morgan', 'hazel.morgan272@campus.edu', 'Pearsons', 'third year', 0, 0),
('Andrew Howard', 'andrew.howard104@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Isabella Peterson', 'isabella.peterson891@student.campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Camila Price', 'camila.price474@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Emily Evans', 'emily.evans985@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Isaac Ramos', 'isaac.ramos440@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Addison James', 'addison.james854@campus.edu', 'Seabury', 'first year', 0, 1),
('Skylar Turner', 'skylar.turner275@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Eleanor Kelly', 'eleanor.kelly291@campus.edu', 'Seabury', 'third year', 0, 0),
('Henry Carter', 'henry.carter273@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Aiden Rodriguez', 'aiden.rodriguez416@campus.edu', 'MAC', 'second year', 0, 0),
('Caleb Cook', 'caleb.cook29@campus.edu', 'Pearsons', 'first year', 0, 0),
('Lucas Nguyen', 'lucas.nguyen580@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Riley Gray', 'riley.gray839@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Hunter Johnson', 'hunter.johnson52@student.campus.edu', 'Seabury', 'first year', 0, 1),
('Leah Morris', 'leah.morris22@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Isaiah Gutierrez', 'isaiah.gutierrez892@campus.edu', 'Draper', 'fourth year', 0, 0),
('Nora Gomez', 'nora.gomez161@student.campus.edu', 'MAC', 'first year', 0, 1),
('Victoria Wright', 'victoria.wright361@campus.edu', 'Draper', 'second year', 0, 0),
('Luna Sanders', 'luna.sanders890@campus.edu', 'Pearsons', 'first year', 0, 0),
('Wyatt Richardson', 'wyatt.richardson58@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Nathan Morgan', 'nathan.morgan797@campus.edu', 'Seabury', 'third year', 0, 0),
('Liam Bennett', 'liam.bennett16@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Christopher Rodriguez', 'christopher.rodriguez771@campus.edu', 'Draper', 'third year', 0, 0),
('Aurora White', 'aurora.white438@campus.edu', 'Pearsons', 'first year', 0, 0),
('Jayden Miller', 'jayden.miller299@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Evelyn Martin', 'evelyn.martin496@campus.edu', 'Off Campus', 'third year', 0, 0),
('Nora Green', 'nora.green479@campus.edu', 'Pearsons', 'second year', 0, 0),
('Gabriel Ramos', 'gabriel.ramos946@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Nora Jackson', 'nora.jackson368@campus.edu', 'MAC', 'fourth year', 0, 0),
('William Collins', 'william.collins747@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Aria Gray', 'aria.gray680@campus.edu', 'Pearsons', 'second year', 0, 0),
('Anthony Thomas', 'anthony.thomas69@campus.edu', 'Draper', 'first year', 0, 0),
('Aaron Smith', 'aaron.smith299@campus.edu', 'Seabury', 'second year', 0, 1),
('Abigail Young', 'abigail.young14@student.campus.edu', 'Draper', 'first year', 0, 0),
('James Hernandez', 'james.hernandez892@campus.edu', 'Pearsons', 'first year', 0, 0),
('Bella Nelson', 'bella.nelson708@student.campus.edu', 'MAC', 'first year', 0, 0),
('Wyatt Jones', 'wyatt.jones266@student.campus.edu', 'Off Campus', 'third year', 0, 1),
('Audrey Alvarez', 'audrey.alvarez641@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Madison Anderson', 'madison.anderson921@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Joseph Davis', 'joseph.davis972@campus.edu', 'MAC', 'first year', 0, 0),
('Claire Cooper', 'claire.cooper26@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Dylan Edwards', 'dylan.edwards179@campus.edu', 'MAC', 'second year', 0, 1),
('Chloe Wood', 'chloe.wood75@student.campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Zoe Gomez', 'zoe.gomez789@campus.edu', 'Off Campus', 'third year', 0, 0),
('Hannah Miller', 'hannah.miller760@campus.edu', 'Pearsons', 'first year', 0, 0),
('Hannah Wilson', 'hannah.wilson330@student.campus.edu', 'Draper', 'second year', 0, 0),
('Jayden Hall', 'jayden.hall724@campus.edu', 'Seabury', 'second year', 0, 1),
('Joseph Gomez', 'joseph.gomez850@student.campus.edu', 'Pearsons', 'third year', 0, 1),
('Andrew Castillo', 'andrew.castillo593@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Jaxon Ramirez', 'jaxon.ramirez456@student.campus.edu', 'Draper', 'first year', 0, 0),
('Levi King', 'levi.king272@campus.edu', 'Pearsons', 'third year', 0, 0),
('Claire Morgan', 'claire.morgan567@campus.edu', 'MAC', 'second year', 0, 0),
('Zoey Chavez', 'zoey.chavez86@student.campus.edu', 'Draper', 'first year', 0, 0),
('Ava Gonzalez', 'ava.gonzalez625@campus.edu', 'Seabury', 'third year', 0, 0),
('Hannah Martinez', 'hannah.martinez396@campus.edu', 'Off Campus', 'second year', 0, 0),
('Grayson Cooper', 'grayson.cooper272@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Aiden Rodriguez', 'aiden.rodriguez446@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Audrey Evans', 'audrey.evans498@student.campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Jaxon Flores', 'jaxon.flores354@campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Skylar Johnson', 'skylar.johnson164@student.campus.edu', 'Draper', 'first year', 0, 0),
('Lucas Thompson', 'lucas.thompson298@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Joseph Torres', 'joseph.torres464@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Skylar Miller', 'skylar.miller522@campus.edu', 'Off Campus', 'first year', 0, 0),
('Luna Ross', 'luna.ross197@student.campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Mia Cruz', 'mia.cruz571@campus.edu', 'Pearsons', 'first year', 0, 0),
('Jackson Phillips', 'jackson.phillips29@campus.edu', 'MAC', 'fourth year', 0, 0),
('Alexander Davis', 'alexander.davis764@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Ella Thompson', 'ella.thompson130@campus.edu', 'Ecovillage', 'first year', 1, 1),
('Luke Wright', 'luke.wright161@student.campus.edu', 'Draper', 'second year', 0, 0),
('Ava Cooper', 'ava.cooper107@student.campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Luna Davis', 'luna.davis846@campus.edu', 'Off Campus', 'first year', 0, 0),
('Henry Cooper', 'henry.cooper195@student.campus.edu', 'Seabury', 'first year', 0, 1),
('Zoey Ramirez', 'zoey.ramirez129@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Christian Roberts', 'christian.roberts48@campus.edu', 'Pearsons', 'second year', 0, 0),
('Henry Lee', 'henry.lee212@campus.edu', 'Seabury', 'third year', 0, 0),
('Lillian Perez', 'lillian.perez628@student.campus.edu', 'MAC', 'third year', 0, 0),
('Christian Jimenez', 'christian.jimenez124@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Christian Cooper', 'christian.cooper176@campus.edu', 'Draper', 'first year', 0, 0),
('Eleanor Davis', 'eleanor.davis718@campus.edu', 'MAC', 'third year', 0, 0),
('Olivia Lee', 'olivia.lee854@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Sophia Flores', 'sophia.flores182@campus.edu', 'MAC', 'second year', 0, 0),
('Christian Sanders', 'christian.sanders783@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Nora James', 'nora.james724@campus.edu', 'Pearsons', 'first year', 0, 0),
('Emily Murphy', 'emily.murphy469@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('William Garcia', 'william.garcia185@student.campus.edu', 'Draper', 'first year', 0, 0),
('Aubrey Rogers', 'aubrey.rogers460@campus.edu', 'Pearsons', 'second year', 0, 0),
('Savannah Price', 'savannah.price551@campus.edu', 'Off Campus', 'second year', 0, 0),
('Thomas Murphy', 'thomas.murphy956@campus.edu', 'MAC', 'fourth year', 0, 0),
('Abigail Reed', 'abigail.reed235@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Christopher Long', 'christopher.long382@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Benjamin Walker', 'benjamin.walker720@student.campus.edu', 'Pearsons', 'second year', 0, 1),
('Riley Cooper', 'riley.cooper294@student.campus.edu', 'Draper', 'first year', 0, 1),
('Lucas Peterson', 'lucas.peterson596@campus.edu', 'Draper', 'third year', 0, 0),
('Samuel Harris', 'samuel.harris427@campus.edu', 'MAC', 'third year', 0, 0),
('Sofia Adams', 'sofia.adams277@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Matthew Mendoza', 'matthew.mendoza14@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Violet Carter', 'violet.carter230@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('William Ross', 'william.ross650@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('David Green', 'david.green240@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Ava Morris', 'ava.morris610@campus.edu', 'Draper', 'second year', 0, 1),
('Natalie Collins', 'natalie.collins645@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Victoria Alvarez', 'victoria.alvarez24@campus.edu', 'Off Campus', 'second year', 0, 0),
('Oliver Cruz', 'oliver.cruz884@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Violet Foster', 'violet.foster84@campus.edu', 'Seabury', 'third year', 0, 1),
('Isaiah Anderson', 'isaiah.anderson55@student.campus.edu', 'Ecovillage', 'second year', 1, 0),
('Aurora Martinez', 'aurora.martinez866@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Andrew Cooper', 'andrew.cooper968@student.campus.edu', 'Off Campus', 'second year', 0, 1),
('Isabella Patel', 'isabella.patel862@campus.edu', 'Draper', 'first year', 0, 0),
('Luke Kelly', 'luke.kelly498@campus.edu', 'Seabury', 'first year', 0, 1),
('Samuel Flores', 'samuel.flores213@campus.edu', 'MAC', 'third year', 0, 0),
('Avery Ross', 'avery.ross879@campus.edu', 'MAC', 'third year', 0, 0),
('Chloe Cruz', 'chloe.cruz450@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Thomas Lopez', 'thomas.lopez766@student.campus.edu', 'MAC', 'second year', 0, 0),
('Zoey Ramirez', 'zoey.ramirez300@campus.edu', 'Off Campus', 'third year', 0, 0),
('Ryan Parker', 'ryan.parker698@campus.edu', 'Draper', 'third year', 0, 0),
('Sofia Ortiz', 'sofia.ortiz934@campus.edu', 'MAC', 'first year', 0, 0),
('Hazel Lopez', 'hazel.lopez956@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Alexander Ortiz', 'alexander.ortiz983@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Victoria Bennett', 'victoria.bennett970@student.campus.edu', 'Draper', 'first year', 0, 1),
('Eleanor Phillips', 'eleanor.phillips93@campus.edu', 'Pearsons', 'second year', 0, 0),
('Stella Rogers', 'stella.rogers534@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Michael Walker', 'michael.walker656@campus.edu', 'MAC', 'first year', 0, 0),
('Benjamin Bailey', 'benjamin.bailey356@campus.edu', 'Off Campus', 'third year', 0, 0),
('Zoey Myers', 'zoey.myers870@student.campus.edu', 'Draper', 'third year', 0, 1),
('Grace Castillo', 'grace.castillo178@campus.edu', 'Pearsons', 'second year', 0, 0),
('Jackson Cox', 'jackson.cox549@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Camila Scott', 'camila.scott643@campus.edu', 'Draper', 'fourth year', 0, 0),
('Charles Robinson', 'charles.robinson906@campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Addison Long', 'addison.long891@campus.edu', 'Ecovillage', 'first year', 1, 0),
('Eleanor Collins', 'eleanor.collins96@campus.edu', 'Off Campus', 'third year', 0, 1),
('Mia Ross', 'mia.ross887@campus.edu', 'Draper', 'second year', 0, 1),
('Noah Wright', 'noah.wright520@student.campus.edu', 'Ecovillage', 'second year', 1, 1),
('Sebastian Harris', 'sebastian.harris42@campus.edu', 'MAC', 'fourth year', 0, 0),
('Claire Johnson', 'claire.johnson540@campus.edu', 'Seabury', 'third year', 0, 1),
('Harper Brooks', 'harper.brooks232@student.campus.edu', 'MAC', 'second year', 0, 0),
('Noah Hernandez', 'noah.hernandez518@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Nathan Green', 'nathan.green390@campus.edu', 'MAC', 'third year', 0, 0),
('Lillian Edwards', 'lillian.edwards62@student.campus.edu', 'MAC', 'second year', 0, 0),
('Layla Ortiz', 'layla.ortiz648@student.campus.edu', 'Seabury', 'first year', 0, 0),
('Christopher Ramos', 'christopher.ramos482@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Lucas Hill', 'lucas.hill519@campus.edu', 'Pearsons', 'third year', 0, 0),
('Luna Adams', 'luna.adams868@student.campus.edu', 'MAC', 'third year', 0, 0),
('Andrew Reed', 'andrew.reed49@campus.edu', 'MAC', 'first year', 0, 0),
('Anthony Kelly', 'anthony.kelly576@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Hannah Hall', 'hannah.hall925@student.campus.edu', 'Pearsons', 'second year', 0, 1),
('Hazel Reed', 'hazel.reed430@campus.edu', 'Draper', 'first year', 0, 0),
('Caleb Bennett', 'caleb.bennett172@campus.edu', 'Seabury', 'third year', 0, 0),
('Harper Ross', 'harper.ross795@campus.edu', 'Off Campus', 'third year', 0, 0),
('Owen Campbell', 'owen.campbell78@campus.edu', 'Pearsons', 'second year', 0, 0),
('Alexander Cruz', 'alexander.cruz696@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Charlotte Price', 'charlotte.price777@campus.edu', 'Seabury', 'fourth year', 0, 1),
('Elijah Howard', 'elijah.howard74@campus.edu', 'Pearsons', 'first year', 0, 0),
('Thomas Campbell', 'thomas.campbell12@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Aurora Cox', 'aurora.cox113@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Claire Scott', 'claire.scott707@student.campus.edu', 'Draper', 'first year', 0, 0),
('Alexander Garcia', 'alexander.garcia573@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Dylan Nelson', 'dylan.nelson135@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Victoria Diaz', 'victoria.diaz671@student.campus.edu', 'Ecovillage', 'second year', 1, 1),
('Charles Jones', 'charles.jones247@campus.edu', 'Seabury', 'first year', 0, 0),
('Sebastian Evans', 'sebastian.evans362@campus.edu', 'Pearsons', 'first year', 0, 1),
('Christian Foster', 'christian.foster37@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Grayson Peterson', 'grayson.peterson394@campus.edu', 'Ecovillage', 'first year', 1, 0),
('David Castillo', 'david.castillo244@campus.edu', 'Draper', 'third year', 0, 1),
('Nora Hall', 'nora.hall734@campus.edu', 'Seabury', 'second year', 0, 0),
('Scarlett Cruz', 'scarlett.cruz30@student.campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Andrew Mendoza', 'andrew.mendoza330@campus.edu', 'Pearsons', 'third year', 0, 0),
('Camila Mitchell', 'camila.mitchell687@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Zoe Edwards', 'zoe.edwards383@student.campus.edu', 'Draper', 'third year', 0, 0),
('Charlotte Brooks', 'charlotte.brooks539@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Mila Baker', 'mila.baker282@campus.edu', 'Draper', 'third year', 0, 0),
('Joseph Garcia', 'joseph.garcia917@campus.edu', 'Draper', 'fourth year', 0, 0),
('Nathan Watson', 'nathan.watson822@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Penelope Thomas', 'penelope.thomas525@student.campus.edu', 'Draper', 'third year', 0, 0),
('Aiden Brown', 'aiden.brown115@campus.edu', 'Draper', 'first year', 0, 0),
('Addison Torres', 'addison.torres805@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Liam Roberts', 'liam.roberts403@campus.edu', 'Off Campus', 'second year', 0, 0),
('Luna Scott', 'luna.scott693@student.campus.edu', 'Draper', 'second year', 0, 0),
('Hazel Scott', 'hazel.scott384@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Madison Alvarez', 'madison.alvarez720@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Camila Smith', 'camila.smith906@student.campus.edu', 'MAC', 'first year', 0, 0),
('Oliver Ramirez', 'oliver.ramirez292@campus.edu', 'Draper', 'fourth year', 0, 0),
('Christian Edwards', 'christian.edwards313@campus.edu', 'MAC', 'third year', 0, 0),
('Ellie Rodriguez', 'ellie.rodriguez823@campus.edu', 'Off Campus', 'third year', 0, 0),
('Hazel Rivera', 'hazel.rivera407@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Bella Sanders', 'bella.sanders731@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Zoey Martinez', 'zoey.martinez720@student.campus.edu', 'MAC', 'fourth year', 0, 1),
('Lucas Campbell', 'lucas.campbell127@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Anthony Jackson', 'anthony.jackson58@student.campus.edu', 'Ecovillage', 'third year', 1, 1),
('Camila Hill', 'camila.hill428@campus.edu', 'Ecovillage', 'third year', 1, 0),
('Liam Turner', 'liam.turner415@campus.edu', 'Draper', 'second year', 0, 0),
('Audrey Reed', 'audrey.reed922@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Carter Perez', 'carter.perez972@campus.edu', 'Seabury', 'second year', 0, 0),
('Isaac Kim', 'isaac.kim512@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Jayden Reed', 'jayden.reed315@campus.edu', 'Pearsons', 'first year', 0, 0),
('Lily Miller', 'lily.miller229@campus.edu', 'MAC', 'first year', 0, 0),
('Bella Lopez', 'bella.lopez703@campus.edu', 'Off Campus', 'second year', 0, 0),
('Jackson Kelly', 'jackson.kelly631@campus.edu', 'Off Campus', 'third year', 0, 0),
('Grace Peterson', 'grace.peterson660@campus.edu', 'MAC', 'third year', 0, 0),
('Ellie Cook', 'ellie.cook820@student.campus.edu', 'Draper', 'third year', 0, 0),
('Charles Robinson', 'charles.robinson929@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Audrey Hughes', 'audrey.hughes965@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Sebastian Jackson', 'sebastian.jackson700@campus.edu', 'Off Campus', 'second year', 0, 0),
('Olivia Jones', 'olivia.jones308@campus.edu', 'Seabury', 'first year', 0, 0),
('Bella Peterson', 'bella.peterson151@campus.edu', 'Off Campus', 'second year', 0, 1),
('Carter Long', 'carter.long274@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Olivia Cruz', 'olivia.cruz355@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Jaxon Evans', 'jaxon.evans618@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Skylar Baker', 'skylar.baker263@student.campus.edu', 'Draper', 'third year', 0, 1),
('Isaiah Green', 'isaiah.green943@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Natalie Sanchez', 'natalie.sanchez531@campus.edu', 'Off Campus', 'third year', 0, 0),
('Ava Rogers', 'ava.rogers709@campus.edu', 'MAC', 'fourth year', 0, 0),
('Layla Adams', 'layla.adams579@campus.edu', 'Pearsons', 'third year', 0, 0),
('Mila Martinez', 'mila.martinez758@campus.edu', 'Seabury', 'second year', 0, 0),
('Ellie Anderson', 'ellie.anderson831@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Jackson Clark', 'jackson.clark922@student.campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Anthony Peterson', 'anthony.peterson133@campus.edu', 'Pearsons', 'first year', 0, 0),
('Violet Ramirez', 'violet.ramirez950@student.campus.edu', 'Pearsons', 'first year', 0, 0),
('Zoe Morgan', 'zoe.morgan551@student.campus.edu', 'Draper', 'first year', 0, 0),
('Aurora Mendoza', 'aurora.mendoza238@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Sofia Evans', 'sofia.evans548@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Sebastian Stewart', 'sebastian.stewart469@student.campus.edu', 'MAC', 'second year', 0, 0),
('Ella Miller', 'ella.miller4@campus.edu', 'Draper', 'third year', 0, 0),
('Jaxon Sanders', 'jaxon.sanders439@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Thomas Parker', 'thomas.parker313@student.campus.edu', 'Draper', 'fourth year', 0, 0),
('Nathan Robinson', 'nathan.robinson154@student.campus.edu', 'MAC', 'second year', 0, 0),
('Emily Rogers', 'emily.rogers253@campus.edu', 'MAC', 'third year', 0, 0),
('Owen Cooper', 'owen.cooper755@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Sophia Wood', 'sophia.wood503@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Joseph Wood', 'joseph.wood922@student.campus.edu', 'Draper', 'second year', 0, 0),
('Natalie Nguyen', 'natalie.nguyen195@campus.edu', 'Ecovillage', 'third year', 1, 0),
('Ryan Perez', 'ryan.perez207@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Skylar Turner', 'skylar.turner8@student.campus.edu', 'Draper', 'second year', 0, 0),
('Avery Scott', 'avery.scott700@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Benjamin Bailey', 'benjamin.bailey158@student.campus.edu', 'Draper', 'first year', 0, 0),
('Lincoln Reyes', 'lincoln.reyes876@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Thomas Allen', 'thomas.allen407@student.campus.edu', 'MAC', 'second year', 0, 0),
('Mateo Hill', 'mateo.hill126@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Dylan Ramirez', 'dylan.ramirez653@campus.edu', 'Off Campus', 'second year', 0, 1),
('Isabella Edwards', 'isabella.edwards46@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Gabriel Bennett', 'gabriel.bennett79@campus.edu', 'MAC', 'fourth year', 0, 0),
('David Wright', 'david.wright445@student.campus.edu', 'MAC', 'second year', 0, 0),
('Savannah Ramos', 'savannah.ramos363@campus.edu', 'Seabury', 'third year', 0, 0),
('Joshua Reyes', 'joshua.reyes553@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Abigail Collins', 'abigail.collins985@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Jaxon Cruz', 'jaxon.cruz79@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Samuel Bailey', 'samuel.bailey935@campus.edu', 'MAC', 'second year', 0, 0),
('William Young', 'william.young10@campus.edu', 'MAC', 'third year', 0, 0),
('Ella Hernandez', 'ella.hernandez940@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Ryan Perez', 'ryan.perez273@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Julian Morales', 'julian.morales330@campus.edu', 'Pearsons', 'second year', 0, 1),
('Isaac Smith', 'isaac.smith138@campus.edu', 'Draper', 'fourth year', 0, 0),
('Lucas Stewart', 'lucas.stewart206@campus.edu', 'Pearsons', 'second year', 0, 1),
('Luna Rivera', 'luna.rivera561@student.campus.edu', 'MAC', 'second year', 0, 0),
('Emma Foster', 'emma.foster814@campus.edu', 'MAC', 'second year', 0, 1),
('Camila Jimenez', 'camila.jimenez351@campus.edu', 'Draper', 'third year', 0, 0),
('Sophia Martinez', 'sophia.martinez171@campus.edu', 'MAC', 'fourth year', 0, 0),
('James Ruiz', 'james.ruiz176@campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Ella Sanchez', 'ella.sanchez316@student.campus.edu', 'Draper', 'second year', 0, 0),
('Josiah Mitchell', 'josiah.mitchell685@campus.edu', 'Draper', 'second year', 0, 1),
('Avery Ortiz', 'avery.ortiz60@campus.edu', 'MAC', 'third year', 0, 1),
('Elijah Brooks', 'elijah.brooks416@student.campus.edu', 'Draper', 'first year', 0, 0),
('Madison Diaz', 'madison.diaz182@campus.edu', 'Off Campus', 'third year', 0, 0),
('Jaxon Ramos', 'jaxon.ramos708@campus.edu', 'MAC', 'second year', 0, 0),
('Addison Bailey', 'addison.bailey470@student.campus.edu', 'Pearsons', 'third year', 0, 1),
('Hazel Parker', 'hazel.parker173@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Addison Richardson', 'addison.richardson541@campus.edu', 'Draper', 'second year', 0, 0),
('Lily Moore', 'lily.moore729@campus.edu', 'Pearsons', 'third year', 0, 0),
('Charlotte Evans', 'charlotte.evans599@student.campus.edu', 'Draper', 'fourth year', 0, 1),
('Lily Hughes', 'lily.hughes793@student.campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Ellie Jimenez', 'ellie.jimenez474@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Joshua Young', 'joshua.young657@student.campus.edu', 'MAC', 'first year', 0, 0),
('Nora Turner', 'nora.turner720@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Isaac Peterson', 'isaac.peterson304@campus.edu', 'Off Campus', 'second year', 0, 0),
('Brooklyn Rivera', 'brooklyn.rivera471@campus.edu', 'Seabury', 'fourth year', 0, 1),
('Elizabeth Sanders', 'elizabeth.sanders586@campus.edu', 'Draper', 'fourth year', 0, 0),
('Henry Anderson', 'henry.anderson734@campus.edu', 'Draper', 'fourth year', 0, 0),
('Isabella Edwards', 'isabella.edwards277@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Grace Gomez', 'grace.gomez218@student.campus.edu', 'Ecovillage', 'first year', 1, 0),
('Skylar Campbell', 'skylar.campbell601@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Lily Rivera', 'lily.rivera7@campus.edu', 'Seabury', 'third year', 0, 0),
('Brooklyn Morales', 'brooklyn.morales194@campus.edu', 'Seabury', 'first year', 0, 0),
('Madison Collins', 'madison.collins592@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Carter Mendoza', 'carter.mendoza540@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Isabella Hughes', 'isabella.hughes416@campus.edu', 'Draper', 'second year', 0, 0),
('Jaxon Ross', 'jaxon.ross217@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Nora Martinez', 'nora.martinez755@student.campus.edu', 'Draper', 'first year', 0, 0),
('Dylan Sanders', 'dylan.sanders166@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Michael Morris', 'michael.morris858@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Ava Torres', 'ava.torres472@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Christopher Morales', 'christopher.morales75@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Isaac Lee', 'isaac.lee370@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Amelia Watson', 'amelia.watson424@campus.edu', 'Pearsons', 'second year', 0, 0),
('Savannah Williams', 'savannah.williams342@campus.edu', 'Off Campus', 'second year', 0, 0),
('Mia Cook', 'mia.cook916@campus.edu', 'Ecovillage', 'third year', 1, 0),
('Liam Miller', 'liam.miller174@student.campus.edu', 'Off Campus', 'fourth year', 0, 0),
('Nathan Diaz', 'nathan.diaz306@campus.edu', 'MAC', 'first year', 0, 0),
('Ella Turner', 'ella.turner129@campus.edu', 'MAC', 'second year', 0, 0),
('Mila Stewart', 'mila.stewart315@campus.edu', 'MAC', 'fourth year', 0, 1),
('Sofia Alvarez', 'sofia.alvarez293@campus.edu', 'Draper', 'second year', 0, 0),
('Carter Castillo', 'carter.castillo758@student.campus.edu', 'Seabury', 'second year', 0, 0),
('Aubrey Price', 'aubrey.price301@campus.edu', 'MAC', 'second year', 0, 0),
('Oliver Phillips', 'oliver.phillips515@campus.edu', 'Pearsons', 'second year', 0, 0),
('James Parker', 'james.parker341@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Riley Cooper', 'riley.cooper643@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Lillian Evans', 'lillian.evans440@campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Sofia Jones', 'sofia.jones849@campus.edu', 'Pearsons', 'fourth year', 0, 0),
('Natalie Cooper', 'natalie.cooper761@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Lincoln Sanchez', 'lincoln.sanchez246@student.campus.edu', 'Seabury', 'fourth year', 0, 0),
('Hazel Clark', 'hazel.clark279@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Emily Wright', 'emily.wright869@student.campus.edu', 'Ecovillage', 'fourth year', 1, 0),
('Isaac Sanchez', 'isaac.sanchez129@campus.edu', 'Off Campus', 'second year', 0, 0),
('Andrew Cruz', 'andrew.cruz969@campus.edu', 'Seabury', 'second year', 0, 0),
('Gabriel Harris', 'gabriel.harris695@campus.edu', 'MAC', 'third year', 0, 0),
('Addison Myers', 'addison.myers86@student.campus.edu', 'Draper', 'first year', 0, 0),
('Stella Robinson', 'stella.robinson385@campus.edu', 'Seabury', 'first year', 0, 0),
('Leah Mendoza', 'leah.mendoza714@campus.edu', 'Draper', 'third year', 0, 0),
('Elizabeth Sanchez', 'elizabeth.sanchez403@student.campus.edu', 'Off Campus', 'first year', 0, 0),
('Oliver Walker', 'oliver.walker578@student.campus.edu', 'Off Campus', 'third year', 0, 0),
('Julian Wright', 'julian.wright436@student.campus.edu', 'MAC', 'third year', 0, 0),
('Ella Foster', 'ella.foster703@campus.edu', 'Ecovillage', 'second year', 1, 0),
('Charlotte Sanchez', 'charlotte.sanchez615@student.campus.edu', 'MAC', 'fourth year', 0, 0),
('Riley Johnson', 'riley.johnson681@campus.edu', 'Draper', 'second year', 0, 0),
('Joseph Allen', 'joseph.allen860@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Jackson Kelly', 'jackson.kelly413@campus.edu', 'Draper', 'fourth year', 0, 1),
('Isabella Reyes', 'isabella.reyes452@campus.edu', 'Pearsons', 'first year', 0, 1),
('Grayson Lewis', 'grayson.lewis886@campus.edu', 'MAC', 'third year', 0, 0),
('Savannah Lee', 'savannah.lee808@student.campus.edu', 'Draper', 'second year', 0, 1),
('Julian Cooper', 'julian.cooper442@campus.edu', 'Seabury', 'second year', 0, 0),
('Hunter Castillo', 'hunter.castillo424@student.campus.edu', 'Off Campus', 'fourth year', 0, 1),
('Aubrey Sanders', 'aubrey.sanders245@student.campus.edu', 'Ecovillage', 'third year', 1, 0),
('Isaac Cruz', 'isaac.cruz813@student.campus.edu', 'Pearsons', 'third year', 0, 0),
('Audrey Taylor', 'audrey.taylor537@campus.edu', 'Draper', 'first year', 0, 0),
('Caleb Gray', 'caleb.gray290@campus.edu', 'Pearsons', 'fourth year', 0, 1),
('Layla Ramirez', 'layla.ramirez990@campus.edu', 'Draper', 'third year', 0, 0),
('David Patel', 'david.patel325@campus.edu', 'Pearsons', 'second year', 0, 0),
('Scarlett Garcia', 'scarlett.garcia570@student.campus.edu', 'Seabury', 'fourth year', 0, 1),
('Lincoln Morris', 'lincoln.morris232@student.campus.edu', 'Pearsons', 'second year', 0, 0),
('Ellie Perez', 'ellie.perez419@campus.edu', 'Pearsons', 'first year', 0, 0),
('Michael Smith', 'michael.smith503@campus.edu', 'MAC', 'second year', 0, 0),
('Skylar Taylor', 'skylar.taylor677@student.campus.edu', 'MAC', 'first year', 0, 0),
('Stella Mendoza', 'stella.mendoza797@campus.edu', 'Seabury', 'fourth year', 0, 0),
('Ellie Stewart', 'ellie.stewart131@student.campus.edu', 'Off Campus', 'second year', 0, 0),
('Christopher Morgan', 'christopher.morgan33@campus.edu', 'MAC', 'second year', 0, 0),
('Jaxon Taylor', 'jaxon.taylor505@student.campus.edu', 'Seabury', 'third year', 0, 0),
('Lincoln Davis', 'lincoln.davis241@campus.edu', 'Draper', 'fourth year', 0, 0),
('Andrew Miller', 'andrew.miller696@student.campus.edu', 'Pearsons', 'first year', 0, 0);
