-- 1C: Insert Programs (Majors/Minors) (Independent Table)
INSERT INTO programs (program_name) VALUES
('Computer Science'),
('Ethics'),
('Mathematics'),
('Economics'),
('Philosophy'),
('Biology'),
('Chemistry'),
('Physics'),
('English'),
('History'),
('Political Science'),
('Psychology'),
('Sociology'),
('Anthropology'),
('Environmental Science'),
('Art History'),
('Theater'),
('Business Administration'),
('Nursing'),
('Engineering'),
('Communications'),
('Foreign Languages'),
('Music'),
('Education'),
('Journalism');
