import re
import random
import os

students = {}

# Parse the previously generated students to respect their randomized IDs
with open(os.path.join(os.path.dirname(__file__), '1b_insert_students.sql'), 'r') as f:
    content = f.read()

pattern = r"\('(.*?)',\s*'(.*?)',\s*'(.*?)',\s*'(.*?)',\s*(\d+),\s*(\d+)\)"
matches = re.finditer(pattern, content)

for idx, match in enumerate(matches, start=1):
    full_name, email, dorm, class_year, is_non_trad, is_intl = match.groups()
    students[idx] = {
        'dorm': dorm,
        'non_trad': int(is_non_trad),
        'intl': int(is_intl),
        'class_year': class_year
    }

TOTAL_RESOURCES = 33
interactions = []

def random_date():
    m = random.randint(1, 12)
    d = random.randint(1, 28)
    return f"2026-{m:02d}-{d:02d}"

# Hidden Problem IDs
LOW_INTL_RES_ID = 4     # Drop-In Writing Tutoring
LOW_NONTRAD_RES_ID = 30 # Free Flu Vaccine Clinic
LOW_DRAPER_RES_ID = 18  # Sunday Evening Dinner

all_sids = list(students.keys())

for res_id in range(1, TOTAL_RESOURCES + 1):
    # Base number of interactions for this resource
    num = random.randint(50, 150)
    
    candidates = []
    # Filter candidates to artificially restrict turnout
    for sid in all_sids:
        s = students[sid]
        
        if res_id == LOW_INTL_RES_ID and s['intl'] == 1:
            if random.random() < 0.98: # 98% exclusion rate for international
                continue
        if res_id == LOW_NONTRAD_RES_ID and s['non_trad'] == 1:
            if random.random() < 0.98: # 98% exclusion rate for non_trad
                continue
        if res_id == LOW_DRAPER_RES_ID and s['dorm'] == 'Draper':
            if random.random() < 0.98: # 98% exclusion rate for Draper
                continue
                
        candidates.append(sid)
        
    # Sample from the available candidates with replacement
    sampled = random.choices(candidates, k=num)
    for sid in sampled:
        note = random.choice(["Attended", "Registered", "Walk-in", "Follow-up needed", ""])
        interactions.append(f"({sid}, {res_id}, '{random_date()}', '{note}')")

sql_content = "-- 3A: Insert Resource Interactions (with hidden problems for SQL practice)\n"
sql_content += "-- Hidden Problems Generated By Setup Script:\n"
sql_content += "-- Resource 4 (Drop-In Writing Tutoring): Extremely low international student participation\n"
sql_content += "-- Resource 30 (Free Flu Vaccine Clinic): Extremely low non-traditional student participation\n"
sql_content += "-- Resource 18 (Sunday Evening Dinner): Extremely low participation from Draper dorm residents\n\n"
sql_content += "INSERT INTO resource_interactions (student_id, resource_id, interaction_date, notes) VALUES\n"
sql_content += ",\n".join(interactions) + ";\n"

output_path = os.path.join(os.path.dirname(__file__), "3a_insert_resource_interactions.sql")
with open(output_path, "w") as f:
    f.write(sql_content)
    
print(f"Generated {len(interactions)} mock interactions.")
